/**
 * 소량 시드 — 개발 확인용.
 *
 * 실행: pnpm harness:seed-small
 *       pnpm harness:seed-small -- --products 20 --locations 30
 *
 * 10만 건짜리 본 시드(P8, harness/seed.ts)와는 목적이 다르다.
 * 이건 화면을 띄워보고 쿼리를 짜보기 위한 최소 데이터다.
 *
 * 실행할 때마다 기존 데이터를 전부 지우고 다시 넣는다.
 * 시드값이 고정돼 있어 같은 옵션이면 항상 같은 데이터가 나온다.
 */

import oracledb from "oracledb";
import bcrypt from "bcryptjs";
import { assertDevDatabase, openConnection, describeTarget, countRows } from "./lib/db.ts";
import {
  createRandom,
  pick,
  intBetween,
  productName,
  recipientName,
  phone,
  address,
  CHANNELS,
} from "./lib/fake.ts";

// ── 옵션 ────────────────────────────────────────────────────────────
// 숫자를 코드에 박지 않는다. 기본값은 P5가 요구한 규모다.

function argInt(name: string, fallback: number): number {
  const index = process.argv.indexOf(`--${name}`);
  if (index === -1) return fallback;
  const parsed = Number.parseInt(process.argv[index + 1] ?? "", 10);
  if (Number.isNaN(parsed) || parsed < 0) {
    throw new Error(`--${name} 값이 올바르지 않습니다: ${process.argv[index + 1]}`);
  }
  return parsed;
}

const OPTIONS = {
  products: argInt("products", 20),
  locations: argInt("locations", 30),
  inventory: argInt("inventory", 50),
  orders: argInt("orders", 10),
  seed: argInt("seed", 20260902),
};

/** 데모 계정. 기획서 11장의 계정과 같다. 비밀번호는 전부 demo1234. */
const DEMO_USERS = [
  { email: "admin@demo.io", name: "데모 관리자", role: "ADMIN" },
  { email: "ops@demo.io", name: "데모 운영자", role: "OPERATOR" },
  { email: "picker@demo.io", name: "데모 작업자", role: "PICKER" },
  { email: "viewer@demo.io", name: "데모 조회자", role: "VIEWER" },
] as const;

const DEMO_PASSWORD = "demo1234";

/** 삭제 순서. 외래키를 참조하는 쪽부터 지운다. */
const TABLES_IN_DELETE_ORDER = [
  "IDEMPOTENCY_KEYS",
  "AUDIT_LOGS",
  "INVENTORY_TRANSACTIONS",
  "SHIPMENTS",
  "PICKING_TASKS",
  "PICKING_WAVES",
  "ORDER_ITEMS",
  "ORDERS",
  "INVENTORY",
  "LOCATIONS",
  "PRODUCTS",
  "USERS",
] as const;

/** 건수를 보여줄 순서. 사람이 읽기 좋은 순서로 둔다. */
const TABLES_TO_REPORT = [
  "USERS",
  "PRODUCTS",
  "LOCATIONS",
  "INVENTORY",
  "ORDERS",
  "ORDER_ITEMS",
] as const;

async function wipe(conn: oracledb.Connection): Promise<void> {
  for (const table of TABLES_IN_DELETE_ORDER) {
    await conn.execute(`DELETE FROM ${table}`);
  }
  await conn.commit();
}

/**
 * IDENTITY 채번을 현재 최대값 다음으로 맞춘다.
 *
 * 이 스크립트는 ID를 직접 넣는다(참조 관계를 만들기 쉬우므로).
 * 그대로 두면 채번은 여전히 1부터라, 나중에 앱이 INSERT할 때 PK가 충돌한다.
 * START WITH LIMIT VALUE는 그 시작값을 max(ID)+1로 다시 잡아준다.
 */
async function resyncIdentity(conn: oracledb.Connection, tables: readonly string[]): Promise<void> {
  for (const table of tables) {
    await conn.execute(
      `ALTER TABLE ${table} MODIFY (ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))`,
    );
  }
}

async function seedUsers(conn: oracledb.Connection): Promise<void> {
  // bcrypt 해시는 느린 게 정상이다(그게 목적). 4명뿐이라 순차로 만든다.
  const rows = await Promise.all(
    DEMO_USERS.map(async (user, index) => ({
      id: index + 1,
      email: user.email,
      name: user.name,
      hash: await bcrypt.hash(DEMO_PASSWORD, 10),
      role: user.role,
    })),
  );

  await conn.executeMany(
    `INSERT INTO USERS (ID, EMAIL, NAME, PASSWORD_HASH, ROLE)
     VALUES (:id, :email, :name, :hash, :role)`,
    rows,
    {
      bindDefs: {
        id: { type: oracledb.NUMBER },
        email: { type: oracledb.STRING, maxSize: 255 },
        name: { type: oracledb.STRING, maxSize: 100 },
        hash: { type: oracledb.STRING, maxSize: 255 },
        role: { type: oracledb.STRING, maxSize: 20 },
      },
    },
  );
}

async function seedProducts(conn: oracledb.Connection, rand: () => number): Promise<void> {
  const rows = Array.from({ length: OPTIONS.products }, (_, index) => {
    const { name, optionName } = productName(rand);
    return {
      id: index + 1,
      sku: `SKU-${10001 + index}`,
      name,
      barcode: `88${String(10000000 + index).padStart(11, "0")}`,
      optionName,
      price: intBetween(rand, 5, 120) * 1000,
    };
  });

  await conn.executeMany(
    `INSERT INTO PRODUCTS (ID, SKU, NAME, BARCODE, OPTION_NAME, UNIT_PRICE)
     VALUES (:id, :sku, :name, :barcode, :optionName, :price)`,
    rows,
    {
      bindDefs: {
        id: { type: oracledb.NUMBER },
        sku: { type: oracledb.STRING, maxSize: 50 },
        name: { type: oracledb.STRING, maxSize: 200 },
        barcode: { type: oracledb.STRING, maxSize: 50 },
        optionName: { type: oracledb.STRING, maxSize: 100 },
        price: { type: oracledb.NUMBER },
      },
    },
  );
}

async function seedLocations(conn: oracledb.Connection): Promise<void> {
  // 코드는 구역-통로-선반-단. SORT_ORDER는 한 방향 순회 순서다.
  // 창고를 A구역부터 통로 순으로 훑는 동선을 그대로 번호로 만든다.
  const rows = Array.from({ length: OPTIONS.locations }, (_, index) => {
    const zoneIndex = Math.floor(index / 12);
    const zone = String.fromCharCode(65 + zoneIndex); // A, B, C...
    const withinZone = index % 12;
    const aisle = Math.floor(withinZone / 4) + 1;
    const rack = (withinZone % 4) + 1;
    const levelNo = (index % 3) + 1;

    return {
      id: index + 1,
      code: `${zone}-${String(aisle).padStart(2, "0")}-${String(rack).padStart(2, "0")}-${levelNo}`,
      zone,
      aisle,
      rack,
      levelNo,
      sortOrder: (index + 1) * 10,
    };
  });

  // 바인드 이름을 :level로 두면 ORA-01745가 난다. LEVEL은 오라클 예약어라
  // 컬럼명뿐 아니라 바인드 변수명으로도 쓸 수 없다.
  await conn.executeMany(
    `INSERT INTO LOCATIONS (ID, CODE, ZONE, AISLE, RACK, LEVEL_NO, SORT_ORDER)
     VALUES (:id, :code, :zone, :aisle, :rack, :levelNo, :sortOrder)`,
    rows,
    {
      bindDefs: {
        id: { type: oracledb.NUMBER },
        code: { type: oracledb.STRING, maxSize: 30 },
        zone: { type: oracledb.STRING, maxSize: 10 },
        aisle: { type: oracledb.NUMBER },
        rack: { type: oracledb.NUMBER },
        levelNo: { type: oracledb.NUMBER },
        sortOrder: { type: oracledb.NUMBER },
      },
    },
  );
}

async function seedInventory(conn: oracledb.Connection, rand: () => number): Promise<void> {
  // (상품, 로케이션) 조합은 유니크다. 중복이 나오지 않게 조합을 미리 만들어 섞는다.
  const pairs: Array<{ productId: number; locationId: number }> = [];
  for (let p = 1; p <= OPTIONS.products; p += 1) {
    for (let l = 1; l <= OPTIONS.locations; l += 1) {
      pairs.push({ productId: p, locationId: l });
    }
  }

  // 시드 고정 셔플(Fisher-Yates).
  for (let i = pairs.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rand() * (i + 1));
    [pairs[i], pairs[j]] = [pairs[j], pairs[i]];
  }

  const wanted = Math.min(OPTIONS.inventory, pairs.length);
  const rows = pairs.slice(0, wanted).map((pair, index) => ({
    id: index + 1,
    ...pair,
    onHand: intBetween(rand, 1, 200),
    // 할당량은 반드시 0으로 시작한다.
    //
    // 여기에 난수를 넣으면 정합성 조건 3(상품별 ORDER_ITEMS.ALLOCATED_QTY 합계 =
    // INVENTORY.QTY_ALLOCATED 합계)이 처음부터 깨진다. 주문은 전부 RECEIVED라
    // 할당된 수량이 0이기 때문이다.
    //
    // 재고 할당은 PL/SQL 프로시저를 거쳐야만 한다(AGENTS.md 절대 규칙).
    // 시드가 할당된 척하는 데이터를 만들어두면 그 규칙을 우회하는 셈이다.
    allocated: 0,
  }));

  await conn.executeMany(
    `INSERT INTO INVENTORY (ID, PRODUCT_ID, LOCATION_ID, QTY_ON_HAND, QTY_ALLOCATED)
     VALUES (:id, :productId, :locationId, :onHand, :allocated)`,
    rows,
    {
      bindDefs: {
        id: { type: oracledb.NUMBER },
        productId: { type: oracledb.NUMBER },
        locationId: { type: oracledb.NUMBER },
        onHand: { type: oracledb.NUMBER },
        allocated: { type: oracledb.NUMBER },
      },
    },
  );
}

async function seedOrders(conn: oracledb.Connection, rand: () => number): Promise<number> {
  // 기준 시각을 고정한다. 매 실행마다 날짜가 바뀌면 같은 데이터가 아니게 된다.
  const baseDate = new Date("2026-09-01T09:00:00+09:00");
  const datePart = "20260901";

  const orders = Array.from({ length: OPTIONS.orders }, (_, index) => {
    const orderedAt = new Date(baseDate.getTime() + index * 17 * 60 * 1000);
    return {
      id: index + 1,
      orderNo: `O-${datePart}-${String(index + 1).padStart(6, "0")}`,
      channel: pick(rand, CHANNELS),
      recipientName: recipientName(rand),
      recipientPhone: phone(rand),
      address: address(rand),
      // 전부 RECEIVED로 둔다. 상태 전이는 lib/order-graph.ts의 transition()만 거쳐야 하므로
      // 시드가 중간 상태를 임의로 만들어두지 않는다.
      status: "RECEIVED",
      orderedAt,
      dueAt: new Date(orderedAt.getTime() + 48 * 60 * 60 * 1000),
    };
  });

  await conn.executeMany(
    `INSERT INTO ORDERS (ID, ORDER_NO, CHANNEL, RECIPIENT_NAME, RECIPIENT_PHONE, ADDRESS,
                         STATUS, ORDERED_AT, DUE_AT)
     VALUES (:id, :orderNo, :channel, :recipientName, :recipientPhone, :address,
             :status, :orderedAt, :dueAt)`,
    orders,
    {
      bindDefs: {
        id: { type: oracledb.NUMBER },
        orderNo: { type: oracledb.STRING, maxSize: 30 },
        channel: { type: oracledb.STRING, maxSize: 30 },
        recipientName: { type: oracledb.STRING, maxSize: 100 },
        recipientPhone: { type: oracledb.STRING, maxSize: 30 },
        address: { type: oracledb.STRING, maxSize: 500 },
        status: { type: oracledb.STRING, maxSize: 20 },
        orderedAt: { type: oracledb.DB_TYPE_TIMESTAMP_TZ },
        dueAt: { type: oracledb.DB_TYPE_TIMESTAMP_TZ },
      },
    },
  );

  // 주문상품. P5가 명시하진 않았지만, 상품 줄이 없는 주문은 할당도 피킹도 걸어볼 수 없다.
  const items: Array<{ id: number; orderId: number; productId: number; qty: number }> = [];
  let itemId = 1;
  for (const order of orders) {
    const lineCount = intBetween(rand, 1, 3);
    const used = new Set<number>();
    for (let i = 0; i < lineCount; i += 1) {
      let productId = intBetween(rand, 1, OPTIONS.products);
      while (used.has(productId)) {
        productId = (productId % OPTIONS.products) + 1;
      }
      used.add(productId);
      items.push({ id: itemId, orderId: order.id, productId, qty: intBetween(rand, 1, 5) });
      itemId += 1;
    }
  }

  await conn.executeMany(
    `INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QTY, ALLOCATED_QTY, PICKED_QTY, STATUS)
     VALUES (:id, :orderId, :productId, :qty, 0, 0, 'PENDING')`,
    items,
    {
      bindDefs: {
        id: { type: oracledb.NUMBER },
        orderId: { type: oracledb.NUMBER },
        productId: { type: oracledb.NUMBER },
        qty: { type: oracledb.NUMBER },
      },
    },
  );

  return items.length;
}

async function main(): Promise<void> {
  const startedAt = Date.now();

  assertDevDatabase();
  console.log(`대상: ${describeTarget()}`);
  console.log(`옵션: ${JSON.stringify(OPTIONS)}`);

  const conn = await openConnection();
  try {
    const rand = createRandom(OPTIONS.seed);

    console.log("기존 데이터를 지웁니다...");
    await wipe(conn);

    console.log("데이터를 넣습니다...");
    await seedUsers(conn);
    await seedProducts(conn, rand);
    await seedLocations(conn);
    await seedInventory(conn, rand);
    const itemCount = await seedOrders(conn, rand);
    await conn.commit();

    await resyncIdentity(conn, [
      "USERS",
      "PRODUCTS",
      "LOCATIONS",
      "INVENTORY",
      "ORDERS",
      "ORDER_ITEMS",
    ]);

    const counts = await countRows(conn, TABLES_TO_REPORT);

    console.log("\n── 결과 ──────────────────────────");
    for (const table of TABLES_TO_REPORT) {
      console.log(`  ${table.padEnd(14)} ${String(counts[table]).padStart(6)} 건`);
    }
    console.log("──────────────────────────────────");
    console.log(`데모 계정 ${DEMO_USERS.length}개, 비밀번호는 전부 ${DEMO_PASSWORD}`);
    console.log(`주문상품 ${itemCount}건 (주문당 1~3줄)`);
    console.log(`소요 ${((Date.now() - startedAt) / 1000).toFixed(1)}초`);

    // 요청한 건수가 실제로 들어갔는지 스크립트가 판정한다. 사람이 눈으로 세지 않는다.
    const expected: Record<string, number> = {
      USERS: DEMO_USERS.length,
      PRODUCTS: OPTIONS.products,
      LOCATIONS: OPTIONS.locations,
      INVENTORY: OPTIONS.inventory,
      ORDERS: OPTIONS.orders,
      ORDER_ITEMS: itemCount,
    };
    const mismatches = TABLES_TO_REPORT.filter((t) => counts[t] !== expected[t]);
    if (mismatches.length > 0) {
      for (const table of mismatches) {
        console.error(`✗ ${table}: 기대 ${expected[table]}건, 실제 ${counts[table]}건`);
      }
      throw new Error("건수가 맞지 않습니다.");
    }

    console.log("✓ 건수 일치");
  } finally {
    await conn.close();
  }
}

main().catch((error: unknown) => {
  console.error("\n✗ 시드 실패");
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
