/**
 * 본 시드 — 10만 건 규모.
 *
 * 실행: pnpm harness:seed
 *       pnpm harness:seed -- --orders 100000 --products 5000 --locations 2000
 *
 * 이 프로젝트가 "10만 건에서 안 끊긴다"고 주장하려면 그 10만 건이 실제로 있어야 한다.
 * 이 스크립트가 그 근거를 만든다.
 *
 * 목표: 5분 이내 완료 (harness.mdc 합격 기준).
 */

import oracledb from "oracledb";
import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { assertDevDatabase, openConnection, describeTarget, countRows } from "./lib/db.ts";
import {
  createRandom,
  pick,
  intBetween,
  orderLineCount,
  productName,
  recipientName,
  phone,
  address,
  CHANNELS,
} from "./lib/fake.ts";

// ── 옵션 ────────────────────────────────────────────────────────────

function argInt(name: string, fallback: number): number {
  const index = process.argv.indexOf(`--${name}`);
  if (index === -1) return fallback;
  const parsed = Number.parseInt(process.argv[index + 1] ?? "", 10);
  if (Number.isNaN(parsed) || parsed < 0) {
    throw new Error(`--${name} 값이 올바르지 않습니다: ${process.argv[index + 1]}`);
  }
  return parsed;
}

const OPTIONS = {
  products: argInt("products", 5000),
  locations: argInt("locations", 2000),
  /** 재고 행 수. 상품 하나가 여러 로케이션에 흩어져 있는 상황을 만든다. */
  inventory: argInt("inventory", 10000),
  orders: argInt("orders", 100000),
  /** 한 번에 보낼 행 수. 너무 크면 메모리를, 너무 작으면 왕복을 낭비한다. */
  batch: argInt("batch", 10000),
  seed: argInt("seed", 20260902),
};

/** 합격 기준: 5분. harness.mdc의 seed 항목. */
const TARGET_SECONDS = 300;

const TABLES_TO_REPORT = [
  "USERS",
  "PRODUCTS",
  "LOCATIONS",
  "INVENTORY",
  "ORDERS",
  "ORDER_ITEMS",
] as const;

const TABLES_IN_DELETE_ORDER = [
  "IDEMPOTENCY_KEYS",
  "AUDIT_LOGS",
  "INVENTORY_TRANSACTIONS",
  "SHIPMENTS",
  "PICKING_TASKS",
  "PICKING_WAVES",
  "ORDER_ITEMS",
  "ORDERS",
  "INVENTORY",
  "LOCATIONS",
  "PRODUCTS",
  "USERS",
] as const;

const DEMO_USERS = [
  { email: "admin@demo.io", name: "데모 관리자", role: "ADMIN" },
  { email: "ops@demo.io", name: "데모 운영자", role: "OPERATOR" },
  { email: "picker@demo.io", name: "데모 작업자", role: "PICKER" },
  { email: "viewer@demo.io", name: "데모 조회자", role: "VIEWER" },
] as const;

// ── 진행률 ──────────────────────────────────────────────────────────

function progress(label: string, done: number, total: number, startedAt: number): void {
  const percent = total === 0 ? 100 : Math.floor((done / total) * 100);
  const elapsed = (Date.now() - startedAt) / 1000;
  const rate = elapsed > 0 ? Math.round(done / elapsed) : 0;
  const line = `  ${label.padEnd(12)} ${String(percent).padStart(3)}%  ${done.toLocaleString()}/${total.toLocaleString()}  ${rate.toLocaleString()}행/초`;
  // 같은 줄을 덮어쓴다. 10만 건을 찍으면 터미널이 스크롤로 넘친다.
  process.stdout.write(`\r${line.padEnd(72)}`);
}

function endProgress(): void {
  process.stdout.write("\n");
}

// ── 삽입 ────────────────────────────────────────────────────────────

async function wipe(conn: oracledb.Connection): Promise<void> {
  for (const table of TABLES_IN_DELETE_ORDER) {
    // TRUNCATE가 DELETE보다 훨씬 빠르지만 외래키가 걸려 있으면 쓸 수 없다.
    // 참조하는 쪽부터 지우면 DELETE로도 문제없다.
    await conn.execute(`DELETE FROM ${table}`);
  }
  await conn.commit();
}

/**
 * 시드가 ID를 직접 넣으므로 IDENTITY 채번을 최대값 다음으로 맞춘다.
 * 그러지 않으면 나중에 앱이 INSERT할 때 PK가 충돌한다.
 */
async function resyncIdentity(conn: oracledb.Connection): Promise<void> {
  for (const table of TABLES_TO_REPORT) {
    await conn.execute(
      `ALTER TABLE ${table} MODIFY (ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))`,
    );
  }
}

async function seedUsers(conn: oracledb.Connection): Promise<void> {
  // 비밀번호 해시는 소량 시드와 같은 값을 쓴다.
  // 10만 건 시드에서 bcrypt를 다시 도는 것은 의미가 없고, 계정은 4개뿐이다.
  const bcrypt = await import("bcryptjs");
  const rows = await Promise.all(
    DEMO_USERS.map(async (user, index) => ({
      id: index + 1,
      email: user.email,
      name: user.name,
      hash: await bcrypt.default.hash("demo1234", 10),
      role: user.role,
    })),
  );

  await conn.executeMany(
    `INSERT INTO USERS (ID, EMAIL, NAME, PASSWORD_HASH, ROLE)
     VALUES (:id, :email, :name, :hash, :role)`,
    rows,
    {
      bindDefs: {
        id: { type: oracledb.NUMBER },
        email: { type: oracledb.STRING, maxSize: 255 },
        name: { type: oracledb.STRING, maxSize: 100 },
        hash: { type: oracledb.STRING, maxSize: 255 },
        role: { type: oracledb.STRING, maxSize: 20 },
      },
    },
  );
  await conn.commit();
}

async function seedProducts(conn: oracledb.Connection, rand: () => number): Promise<void> {
  const startedAt = Date.now();
  const sql = `INSERT INTO PRODUCTS (ID, SKU, NAME, BARCODE, OPTION_NAME, UNIT_PRICE)
               VALUES (:id, :sku, :name, :barcode, :optionName, :price)`;
  const bindDefs = {
    id: { type: oracledb.NUMBER },
    sku: { type: oracledb.STRING, maxSize: 50 },
    name: { type: oracledb.STRING, maxSize: 200 },
    barcode: { type: oracledb.STRING, maxSize: 50 },
    optionName: { type: oracledb.STRING, maxSize: 100 },
    price: { type: oracledb.NUMBER },
  };

  for (let offset = 0; offset < OPTIONS.products; offset += OPTIONS.batch) {
    const size = Math.min(OPTIONS.batch, OPTIONS.products - offset);
    const rows = Array.from({ length: size }, (_, i) => {
      const index = offset + i;
      const { name, optionName } = productName(rand);
      return {
        id: index + 1,
        sku: `SKU-${String(10001 + index).padStart(6, "0")}`,
        name,
        barcode: `88${String(10000000 + index).padStart(11, "0")}`,
        optionName,
        price: intBetween(rand, 5, 120) * 1000,
      };
    });
    await conn.executeMany(sql, rows, { bindDefs });
    await conn.commit();
    progress("PRODUCTS", offset + size, OPTIONS.products, startedAt);
  }
  endProgress();
}

async function seedLocations(conn: oracledb.Connection): Promise<void> {
  const startedAt = Date.now();
  const sql = `INSERT INTO LOCATIONS (ID, CODE, ZONE, AISLE, RACK, LEVEL_NO, SORT_ORDER)
               VALUES (:id, :code, :zone, :aisle, :rack, :levelNo, :sortOrder)`;
  // :level은 쓸 수 없다. LEVEL은 오라클 예약어라 바인드 이름으로도 거부된다(ORA-01745).
  const bindDefs = {
    id: { type: oracledb.NUMBER },
    code: { type: oracledb.STRING, maxSize: 30 },
    zone: { type: oracledb.STRING, maxSize: 10 },
    aisle: { type: oracledb.NUMBER },
    rack: { type: oracledb.NUMBER },
    levelNo: { type: oracledb.NUMBER },
    sortOrder: { type: oracledb.NUMBER },
  };

  // 구역 8개 × 통로 · 선반 · 단. SORT_ORDER는 한 방향 순회 순서 그대로다.
  const ZONES = 8;
  const perZone = Math.ceil(OPTIONS.locations / ZONES);

  for (let offset = 0; offset < OPTIONS.locations; offset += OPTIONS.batch) {
    const size = Math.min(OPTIONS.batch, OPTIONS.locations - offset);
    const rows = Array.from({ length: size }, (_, i) => {
      const index = offset + i;
      const zoneIndex = Math.floor(index / perZone);
      const withinZone = index % perZone;
      const aisle = Math.floor(withinZone / 20) + 1;
      const rack = Math.floor((withinZone % 20) / 4) + 1;
      const levelNo = (withinZone % 4) + 1;
      const zone = String.fromCharCode(65 + zoneIndex);
      return {
        id: index + 1,
        code: `${zone}-${String(aisle).padStart(2, "0")}-${String(rack).padStart(2, "0")}-${levelNo}`,
        zone,
        aisle,
        rack,
        levelNo,
        sortOrder: (index + 1) * 10,
      };
    });
    await conn.executeMany(sql, rows, { bindDefs });
    await conn.commit();
    progress("LOCATIONS", offset + size, OPTIONS.locations, startedAt);
  }
  endProgress();
}

/** 재고를 넣고, 넣은 실재고의 총합을 돌려준다. 나중에 DB 합계와 대조한다. */
async function seedInventory(conn: oracledb.Connection, rand: () => number): Promise<number> {
  const startedAt = Date.now();
  const sql = `INSERT INTO INVENTORY (ID, PRODUCT_ID, LOCATION_ID, QTY_ON_HAND, QTY_ALLOCATED)
               VALUES (:id, :productId, :locationId, :onHand, 0)`;
  const bindDefs = {
    id: { type: oracledb.NUMBER },
    productId: { type: oracledb.NUMBER },
    locationId: { type: oracledb.NUMBER },
    onHand: { type: oracledb.NUMBER },
  };

  // (상품, 로케이션)은 유니크다(UX_INV_PROD_LOC).
  // 곱집합을 만들어 섞기에는 상품 5천 × 로케이션 2천 = 1천만 쌍이라 너무 크다.
  //
  // 대신 상품마다 시작 로케이션을 달리하고 거기서 1씩 이어 붙인다.
  // 한 상품 안에서 로케이션 번호가 연속하므로 중복이 생길 수 없다.
  // (처음에는 n에 상품 수를 곱해 흩뿌렸는데, 상품 수가 로케이션 수의 배수이면
  //  나머지가 같은 값으로 되돌아와 ORA-00001이 났다.)
  const perProduct = Math.max(1, Math.round(OPTIONS.inventory / OPTIONS.products));
  if (perProduct > OPTIONS.locations) {
    throw new Error(
      `상품당 재고 행(${perProduct})이 로케이션 수(${OPTIONS.locations})보다 많습니다. ` +
        `한 상품이 같은 로케이션에 두 번 놓일 수 없으므로 --inventory를 줄이거나 --locations를 늘리세요.`,
    );
  }

  let expectedOnHandSum = 0;
  let inserted = 0;
  let rows: Array<{ id: number; productId: number; locationId: number; onHand: number }> = [];

  for (
    let productId = 1;
    productId <= OPTIONS.products && inserted < OPTIONS.inventory;
    productId += 1
  ) {
    // 상품마다 다른 지점에서 시작해 창고 전체에 골고루 퍼지게 한다.
    const start = ((productId - 1) * perProduct) % OPTIONS.locations;
    for (let n = 0; n < perProduct && inserted < OPTIONS.inventory; n += 1) {
      const locationId = ((start + n) % OPTIONS.locations) + 1;
      const onHand = intBetween(rand, 1, 500);
      expectedOnHandSum += onHand;
      inserted += 1;
      rows.push({ id: inserted, productId, locationId, onHand });

      if (rows.length >= OPTIONS.batch) {
        await conn.executeMany(sql, rows, { bindDefs });
        await conn.commit();
        rows = [];
        progress("INVENTORY", inserted, OPTIONS.inventory, startedAt);
      }
    }
  }

  if (rows.length > 0) {
    await conn.executeMany(sql, rows, { bindDefs });
    await conn.commit();
  }
  progress("INVENTORY", inserted, OPTIONS.inventory, startedAt);
  endProgress();

  return expectedOnHandSum;
}

/** 주문과 주문상품을 함께 넣고, 만든 주문상품 수를 돌려준다. */
async function seedOrders(conn: oracledb.Connection, rand: () => number): Promise<number> {
  const startedAt = Date.now();

  const orderSql = `INSERT INTO ORDERS (ID, ORDER_NO, CHANNEL, RECIPIENT_NAME, RECIPIENT_PHONE,
                                        ADDRESS, STATUS, ORDERED_AT, DUE_AT)
                    VALUES (:id, :orderNo, :channel, :recipientName, :recipientPhone,
                            :address, 'RECEIVED', :orderedAt, :dueAt)`;
  const orderBindDefs = {
    id: { type: oracledb.NUMBER },
    orderNo: { type: oracledb.STRING, maxSize: 30 },
    channel: { type: oracledb.STRING, maxSize: 30 },
    recipientName: { type: oracledb.STRING, maxSize: 100 },
    recipientPhone: { type: oracledb.STRING, maxSize: 30 },
    address: { type: oracledb.STRING, maxSize: 500 },
    orderedAt: { type: oracledb.DB_TYPE_TIMESTAMP_TZ },
    dueAt: { type: oracledb.DB_TYPE_TIMESTAMP_TZ },
  };

  const itemSql = `INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QTY, ALLOCATED_QTY, PICKED_QTY, STATUS)
                   VALUES (:id, :orderId, :productId, :qty, 0, 0, 'PENDING')`;
  const itemBindDefs = {
    id: { type: oracledb.NUMBER },
    orderId: { type: oracledb.NUMBER },
    productId: { type: oracledb.NUMBER },
    qty: { type: oracledb.NUMBER },
  };

  // 주문 시각의 기준점을 고정한다. 매 실행마다 날짜가 바뀌면 같은 데이터가 아니게 된다.
  // 최근 30일에 걸쳐 흩어놓아 기간 필터를 시험해볼 수 있게 한다.
  const baseMs = new Date("2026-09-01T09:00:00+09:00").getTime();
  const spanMs = 30 * 24 * 60 * 60 * 1000;

  let itemId = 0;

  for (let offset = 0; offset < OPTIONS.orders; offset += OPTIONS.batch) {
    const size = Math.min(OPTIONS.batch, OPTIONS.orders - offset);
    const orders = [];
    const items = [];

    for (let i = 0; i < size; i += 1) {
      const index = offset + i;
      const id = index + 1;
      const orderedAt = new Date(baseMs - Math.floor(rand() * spanMs));
      const stamp = orderedAt.toISOString().slice(0, 10).replace(/-/g, "");

      orders.push({
        id,
        // 날짜 접두 + 일련번호. 시퀀스를 쓰면 실행할 때마다 번호가 달라져
        // "같은 옵션이면 같은 데이터"가 성립하지 않는다.
        orderNo: `O-${stamp}-${String(id).padStart(6, "0")}`,
        channel: pick(rand, CHANNELS),
        recipientName: recipientName(rand),
        recipientPhone: phone(rand),
        address: address(rand),
        orderedAt,
        dueAt: new Date(orderedAt.getTime() + 48 * 60 * 60 * 1000),
      });

      // 주문당 상품 1~5줄. 같은 상품이 한 주문에 두 번 들어가지 않게 한다.
      const lineCount = orderLineCount(rand);
      const used = new Set<number>();
      for (let n = 0; n < lineCount; n += 1) {
        let productId = intBetween(rand, 1, OPTIONS.products);
        while (used.has(productId)) {
          productId = (productId % OPTIONS.products) + 1;
        }
        used.add(productId);
        itemId += 1;
        items.push({ id: itemId, orderId: id, productId, qty: intBetween(rand, 1, 5) });
      }
    }

    await conn.executeMany(orderSql, orders, { bindDefs: orderBindDefs });
    // 주문상품이 25만 건이라 한 배치가 배치 크기를 넘을 수 있다. 나눠 보낸다.
    for (let s = 0; s < items.length; s += OPTIONS.batch) {
      await conn.executeMany(itemSql, items.slice(s, s + OPTIONS.batch), {
        bindDefs: itemBindDefs,
      });
    }
    await conn.commit();

    progress("ORDERS", offset + size, OPTIONS.orders, startedAt);
  }
  endProgress();

  return itemId;
}

// ── 결과 저장 ───────────────────────────────────────────────────────

type Metric = {
  key: string;
  unit: string;
  value: number;
  target: number | null;
  pass: boolean;
};

async function writeResult(result: unknown): Promise<string> {
  const dir = path.join(import.meta.dirname, "results");
  await mkdir(dir, { recursive: true });
  const date = new Date().toISOString().slice(0, 10);
  const file = path.join(dir, `${date}-seed.json`);
  await writeFile(file, `${JSON.stringify(result, null, 2)}\n`, "utf8");
  return file;
}

// ── 본체 ────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const startedAt = Date.now();

  assertDevDatabase();
  console.log(`대상: ${describeTarget()}`);
  console.log(`옵션: ${JSON.stringify(OPTIONS)}`);
  console.log(`목표: ${TARGET_SECONDS}초 이내\n`);

  const conn = await openConnection();
  try {
    const rand = createRandom(OPTIONS.seed);

    console.log("기존 데이터를 지웁니다...");
    await wipe(conn);

    await seedUsers(conn);
    await seedProducts(conn, rand);
    await seedLocations(conn);
    const expectedOnHandSum = await seedInventory(conn, rand);
    const itemCount = await seedOrders(conn, rand);

    console.log("\nIDENTITY 채번을 맞춥니다...");
    await resyncIdentity(conn);

    const elapsedSeconds = (Date.now() - startedAt) / 1000;

    // ── 검증 ──
    const counts = await countRows(conn, TABLES_TO_REPORT);

    // 합격 기준의 "재고 합계 일치".
    // 넣으려 한 실재고 총합과 DB에 들어간 총합이 같아야 한다.
    const sums = await conn.execute<{ ON_HAND: number; INV_ALLOC: number; ITEM_ALLOC: number }>(
      `SELECT (SELECT NVL(SUM(QTY_ON_HAND), 0)    FROM INVENTORY)   AS ON_HAND,
              (SELECT NVL(SUM(QTY_ALLOCATED), 0)  FROM INVENTORY)   AS INV_ALLOC,
              (SELECT NVL(SUM(ALLOCATED_QTY), 0)  FROM ORDER_ITEMS) AS ITEM_ALLOC
         FROM DUAL`,
      {},
      { outFormat: oracledb.OUT_FORMAT_OBJECT },
    );
    const row = sums.rows?.[0];
    const onHandSum = row?.ON_HAND ?? -1;
    const invAllocated = row?.INV_ALLOC ?? -1;
    const itemAllocated = row?.ITEM_ALLOC ?? -1;

    console.log("\n── 결과 ──────────────────────────────");
    for (const table of TABLES_TO_REPORT) {
      console.log(`  ${table.padEnd(14)} ${counts[table].toLocaleString().padStart(9)} 건`);
    }
    console.log("──────────────────────────────────────");
    console.log(`  소요 시간      ${elapsedSeconds.toFixed(1)}초 (목표 ${TARGET_SECONDS}초)`);
    console.log(`  실재고 합계    ${onHandSum.toLocaleString()}`);
    console.log(`  할당 합계      재고 ${invAllocated} / 주문상품 ${itemAllocated}`);

    const expected: Record<string, number> = {
      USERS: DEMO_USERS.length,
      PRODUCTS: OPTIONS.products,
      LOCATIONS: OPTIONS.locations,
      INVENTORY: OPTIONS.inventory,
      ORDERS: OPTIONS.orders,
      ORDER_ITEMS: itemCount,
    };

    const metrics: Metric[] = [
      {
        key: "elapsedSeconds",
        unit: "s",
        value: Number(elapsedSeconds.toFixed(1)),
        target: TARGET_SECONDS,
        pass: elapsedSeconds <= TARGET_SECONDS,
      },
      ...TABLES_TO_REPORT.map((table) => ({
        key: `rows.${table}`,
        unit: "rows",
        value: counts[table],
        target: expected[table],
        pass: counts[table] === expected[table],
      })),
      {
        key: "inventory.onHandSum",
        unit: "qty",
        value: onHandSum,
        target: expectedOnHandSum,
        pass: onHandSum === expectedOnHandSum,
      },
      {
        // 정합성 조건 3의 출발점. 시드 직후에는 양쪽 다 0이어야 한다.
        // 할당은 PL/SQL 프로시저만 할 수 있으므로 시드가 만들어두지 않는다.
        key: "allocated.matches",
        unit: "qty",
        value: invAllocated,
        target: itemAllocated,
        pass: invAllocated === itemAllocated && invAllocated === 0,
      },
    ];

    const failed = metrics.filter((metric) => !metric.pass);
    const result = {
      name: "seed",
      runAt: new Date().toISOString(),
      conditions: { ...OPTIONS, target: `${TARGET_SECONDS}s`, orderItems: itemCount },
      metrics,
      pass: failed.length === 0,
    };

    const file = await writeResult(result);
    console.log(`\n결과 저장: ${path.relative(process.cwd(), file)}`);

    if (failed.length > 0) {
      console.error("\n✗ 기준 미달");
      for (const metric of failed) {
        console.error(`  ${metric.key}: ${metric.value} (기준 ${metric.target})`);
      }
      process.exitCode = 1;
      return;
    }

    console.log("✓ 전부 통과");
  } finally {
    await conn.close();
  }
}

main().catch((error: unknown) => {
  console.error("\n✗ 시드 실패");
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
