-- PickFlow 스키마 — 시퀀스
--
-- 02_indexes.sql 다음에 실행한다. 두 번 실행해도 깨지지 않는다.
--
-- 테이블 PK는 GENERATED BY DEFAULT AS IDENTITY로 채번하므로 시퀀스가 필요 없다.
-- 여기 있는 것은 사람이 읽는 번호(주문번호·웨이브번호) 전용이다.

-- 주문번호 채번. 기획서 6장의 규칙: 시퀀스 + 'O-YYYYMMDD-' 접두.
-- 예) O-20260828-000001
--
-- CACHE를 크게 잡는다. 시드 하네스가 10만 건을 배치로 넣을 때
-- 캐시가 작으면 채번이 병목이 된다. 번호에 구멍이 생기는 것은 상관없다.
CREATE SEQUENCE IF NOT EXISTS SEQ_ORDERS
  START WITH 1
  INCREMENT BY 1
  CACHE 1000
  NOCYCLE;

-- 웨이브 번호 채번. 예) W-20260828-0001
CREATE SEQUENCE IF NOT EXISTS SEQ_PICKING_WAVES
  START WITH 1
  INCREMENT BY 1
  CACHE 100
  NOCYCLE;
