-- PickFlow 스키마 — 전체 삭제 (개발용 초기화)
--
-- ⚠ 이 스크립트는 모든 데이터를 지운다. 개발·데모 DB에서만 실행한다.
-- ⚠ 운영 DB에 붙어 있지 않은지 먼저 확인할 것.
--
-- 실행 후 01 → 02 → 03 순서로 다시 만들면 빈 스키마가 된다.
-- 두 번 실행해도 깨지지 않는다 (IF EXISTS).

-- 외래키를 참조하는 쪽부터 지운다.
-- CASCADE CONSTRAINTS를 붙여 남은 참조 제약도 함께 정리한다.
-- PURGE는 휴지통을 건너뛴다. 안 붙이면 BIN$... 객체가 쌓여 재생성 시 이름이 충돌한다.

DROP TABLE IF EXISTS IDEMPOTENCY_KEYS       CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS AUDIT_LOGS             CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS INVENTORY_TRANSACTIONS CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS SHIPMENTS              CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS PICKING_TASKS          CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS PICKING_WAVES          CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS ORDER_ITEMS            CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS ORDERS                 CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS INVENTORY              CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS LOCATIONS              CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS PRODUCTS               CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS USERS                  CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE IF EXISTS SEQ_PICKING_WAVES;
DROP SEQUENCE IF EXISTS SEQ_ORDERS;
